conf/application.conf, conf/messages-ecc.cy
Add dummy messages-ecc.cy file for testing
=> ECC-72 - env. specific link for get EORI

.gitignore, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/JourneyTypeFromUrl.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/auth/AuthRedirectSupport.scala, conf/application.conf, test/unit/controllers/JourneyTypeFromUrlSpec.scala, test/unit/controllers/registration/HowCanWeIdentifyYouControllerSpec.scala, test/unit/controllers/registration/MatchingIdControllerSpec.scala, test/unit/controllers/subscription/DisclosePersonalDetailsConsentControllerSpec.scala, test/util/ControllerSpec.scala
(/<service>/subscribe or /<service>/register)
=> BAU - change auth login to have a single 'continue' url

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/ApplicationController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/EnrolmentAlreadyExistsController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/enrolment_pending_against_group_id.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/registration_exists_group.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/sub01_outcome_processing.scala.html, conf/messages-ecc.cy, conf/messages-ecc.en, conf/prod.routes, test/common/pages/RegistrationProcessingPage.scala, test/unit/controllers/ApplicationControllerSpec.scala, test/unit/controllers/EnrolmentAlreadyExistsControllerSpec.scala, test/unit/controllers/EnrolmentPendingAgainstGroupIdControllerSpec.scala, test/unit/controllers/registration/UserLocationControllerSpec.scala, test/unit/views/EnrolmentPendingAgainstGroupIdViewSpec.scala, test/unit/views/subscription/Sub01OutcomeProcessingSpec.scala
- Someone in your company has already applied
- Already enrolled. Ask team member
=> ECC-136 - update content for two error pages

HOWTOADDSERVICE.md, app/uk/gov/hmrc/eoricommoncomponent/frontend/models/Service.scala, conf/application.conf, test/unit/util/RequireSpec.scala
Also removed redundant "name" parameter
=> BAU - update "How to add service"

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/ConfirmContactDetailsController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/SubscriptionRecoveryController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/subscription/Sub02Controller.scala, conf/prod.routes, test/unit/controllers/registration/ConfirmContactDetailsControllerSpec.scala, test/unit/controllers/registration/SubscriptionRecoveryControllerSpec.scala, test/unit/controllers/subscription/Sub02ControllerGetAnEoriSpec.scala
=> BAU - add service part to the register journey end-state urls

app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/MatchingServiceConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/RegisterWithEoriAndIdConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/RegisterWithoutIdConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/RegistrationDisplayConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/Save4LaterConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/SubscriptionServiceConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/SubscriptionStatusConnector.scala, test/integration/Save4LaterConnectorSpec.scala
- remove "customs" from audit event types
- remove unnecessary duplicate information i.e. "txName" field
=> ECC-234 update audit events

app/assets/css/custom.css, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/helpers/languageSelect.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/partials/header.scala.html, conf/messages-ecc.cy, conf/messages-ecc.en, test/unit/views/partials/HeaderSpec.scala
This replicates the Welsh laguage toggle html found here - https://design.tax.service.gov.uk/hmrc-design-patterns/welsh-language-toggle/ without using hmrcFrontend.
=> ECC-324 - accessible language toggle.

app/assets/template/govuk-template-print.css, app/assets/template/govuk-template.css
- copy of https://www.tax.service.gov.uk/template/assets/stylesheets/govuk-template.css
Also fixes ECC-325 (header logo)
=> ECC-349 - update govuk-templates from latest

app/assets/javascripts/custom.js, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/layout.scala.html
Also fix centered content for IE11
=> ECC-343 - initialise details component

conf/messages.cy
Better fix would be to remove html from messages but quick fix is needed
=> ECC-366 - fix a tags in Welsh message files

app/assets/css/custom.css, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/registration/confirm_contact_details.scala.html, conf/messages-ecc.cy, conf/messages-ecc.en, test/common/pages/matching/ConfirmPage.scala, test/unit/controllers/address/AddressControllerSpec.scala, test/unit/controllers/registration/ConfirmContactDetailsControllerSpec.scala, test/unit/views/registration/ConfirmContactDetailsViewSpec.scala
This is a "Register" only page so Welsh translations not required immediately.
=> ECC-317 - changes to address confirmation page

app/assets/css/custom.css
This is untested - will require testing on Windows once deployed to development
=> ECC-353 - fix for high contrast mode

app/uk/gov/hmrc/eoricommoncomponent/frontend/config/AppConfig.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/RegisterWithEoriAndIdController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/forms/FormUtils.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/migration/check_your_details.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/registration/check_your_details_register.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/contact_details.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/existing_match_subscribe_rcm.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/reg06_eori_already_linked.scala.html, conf/application.conf, conf/messages-ecc.cy, conf/messages.cy, test/unit/controllers/registration/RegisterWithEoriAndIdControllerSpec.scala, test/unit/views/subscription/Reg06EoriAlreadyLinkedSpec.scala
- display date months in Welsh
- provide Welsh help urls where available
=> ECC-368 - Welsh language content fixes

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/AddressController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/ConfirmContactDetailsController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/messaging/mdgModels.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/messaging/subscription/ContactInformation.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/messaging/subscription/EstablishmentAddress.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/messaging/subscription/SubscriptionCreateRequest.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/forms/FormValidation.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/CdsSubscriber.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/SubscriptionDetailsService.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/SubscriptionService.scala, test/unit/controllers/address/AddressControllerSpec.scala, test/unit/controllers/registration/ConfirmContactDetailsControllerSpec.scala, test/unit/services/subscription/CdsSubscriberSpec.scala, test/unit/services/subscription/SubscriptionServiceSpec.scala, test/unit/services/subscription/SubscriptionServiceTestData.scala
This is a port of CDS change https://github.com/hmrc/customs-rosm-frontend/pull/864/files
=> ECC-297 - Failure due to missing postcode in REG01 response

conf/application.conf
Reverts hmrc/eori-common-component-frontend#349
=> Revert "ECC-917: Adding service config for cds"

app/uk/gov/hmrc/eoricommoncomponent/frontend/config/AppConfig.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/Instrumentable.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/RegisterWithEoriAndIdConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/SubscriptionServiceConnector.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/TestHelperController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/PayloadCache.scala, conf/logback.xml, conf/prod.routes
* Added instrumentation to connectors to support payload tests
=> ECC-1046: Added instrumentation to connectors and test helper endpoint

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/RegisterWithEoriAndIdController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/reg06_eori_already_linked.scala.html, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/reg06_id_already_linked.scala.html, conf/messages-ecc.cy, conf/messages-ecc.en, test/unit/controllers/registration/RegisterWithEoriAndIdControllerSpec.scala, test/unit/views/subscription/Reg06EoriAlreadyLinkedSpec.scala, test/unit/views/subscription/Reg06IdAlreadyLinkedSpec.scala
Changes to support updated error messages: https://jira.tools.tax.service.gov.uk/browse/ECC-1204
=> ECC-1204 changes to support new error messages

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/migration/NameIdOrgController.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/SubscriptionBusinessService.scala, app/uk/gov/hmrc/eoricommoncomponent/frontend/views/migration/nameId.scala.html, conf/messages.cy, conf/messages.en, test/unit/config/SessionTimeoutSpec.scala, test/unit/controllers/migration/NameIDOrgControllerSpec.scala
Reverts hmrc/eori-common-component-frontend#432
=> Revert "ECC-1399"

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/unable_to_use_id.scala.html, conf/messages-ecc.cy, conf/messages-ecc.en, test/unit/views/UnableToUseIdViewSpec.scala
Reverts hmrc/eori-common-component-frontend#458
=> Revert "ECC-1380"

build.sbt
Adding additional compiler warnings to show us unused code.
=> ECC-1814 adding compiler warnings

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/migration/how_can_we_identify_you.scala.html
Fix also applied to Registration https://github.com/hmrc/eori-common-component-registration-frontend/pull/347
=> ECC-1923: Fix for validation error message not linking to field
