hmrc/eori-common-component-frontend

app/uk/gov/hmrc/customs/rosmfrontend/config/AppConfig.scala
app/uk/gov/hmrc/customs/rosmfrontend/controllers/RegisterRedirectController.scala
app/uk/gov/hmrc/customs/rosmfrontend/modules/EccMessagesApiProvider.scala
app/uk/gov/hmrc/customs/rosmfrontend/modules/MessagesApiProviderModule.scala
app/uk/gov/hmrc/customs/rosmfrontend/modules/MovementsMessagesApiProvider.scala
app/uk/gov/hmrc/customs/rosmfrontend/views/migration/what_is_your_eori.scala.html
conf/application.conf
conf/messages-ecc.en
conf/messages.cy
conf/messages.en
conf/prod.routes
test/unit/controllers/RegisterRedirectControllerSpec.scala
test/unit/controllers/subscription/WhatIsYourEoriControllerSpec.scala
test/unit/views/subscription/WhatIsYourEoriSpec.scala

Add's a link to page for users to get an EORI
- links to existing "Get an EORI" (Register for CDS) service via an internal re-direct
- added support for multiple messages files.  New or changed message keys can be added to `messages-ecc.en` so that we should have less to translate.
TODO - add tests

ECC-72 - dont have EORI link

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/config/AppConfig.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/eori_enrol_success.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/helpers/feedback.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/partials/header.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/registration_exists.scala.html
conf/application.conf
conf/messages-ecc.cy
conf/messages-ecc.en
conf/prod.routes
test/unit/config/AppConfigSpec.scala
test/unit/controllers/subscription/Sub02ControllerGetAnEoriSpec.scala
test/unit/controllers/subscription/Sub02ControllerRegisterExistingSpec.scala
test/unit/views/EoriEnrolSuccessSpec.scala
test/unit/views/partials/HeaderSpec.scala
test/unit/views/subscription/Reg06EoriAlreadyLinkedSpec.scala
test/unit/views/subscription/Sub02EoriAlreadyAssociatedSpec.scala
test/unit/views/subscription/Sub02SubscriptionInProgressSpec.scala
test/util/builders/SessionBuilder.scala

- Header and sign-out link for 'check_existing_eori' and 'confirmation'
- Fix content for 'confirmation' with prototype
- Add Continue button/link to 'confirmation' and 'enrolment-already-exists'

ECC-96 - content fixes

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/SubscriptionRecoveryController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/subscription/RecipientDetails.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/CdsSubscriber.scala
test/base/Injector.scala
test/integration/HandleSubscriptionConnectorSpec.scala
test/unit/controllers/registration/RegisterWithEoriAndIdControllerSpec.scala
test/unit/controllers/subscription/Sub02ControllerGetAnEoriSpec.scala
test/unit/services/subscription/CdsSubscriberSpec.scala
test/unit/services/subscription/HandleSubscriptionServiceSpec.scala

This PR adds a friendly service name and users language to the RecipientDetails object persisted to mongo.

ECC-11 - changes to support new email templates

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/ApplicationController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/EnrolmentAlreadyExistsController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/HasExistingEoriController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/JourneyTypeFromUrl.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/auth/AccessController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/auth/AuthAction.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/models/Journey.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/models/Service.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/JourneyExtractor.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/ServiceName.scala
test/unit/allowlist/AllowlistVerificationSpec.scala
test/unit/allowlist/AllowlistVerificationWithEnrolmentsSpec.scala
test/unit/controllers/ApplicationControllerSpec.scala
test/unit/controllers/HasExistingEoriControllerSpec.scala
test/util/builders/SessionBuilder.scala

This is done by moving the check for existing enrolment for service to AuthAction - i.e. every page will be protected with this check.
We therefore need to _allow_ access with (e.g. ATaR) enrolment to confirmation and you are enrolled page.

BAU prevent user going back from auto-enrol confirmation

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/SubscriptionService.scala
test/unit/services/subscription/SubscriptionServiceSpec.scala

These are the minimum changes I believe we need to make.  The "093" is just another error that we don't need to specifically handle.  This change just adds the returned 'statusText' to our generic message and logs it at ERROR level.

ECC-165 - handle 093 error response

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/subscription/VatGroupController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/models/Service.scala
conf/application.conf
test/unit/config/AppConfigSpec.scala
test/unit/filters/RouteFilterSpec.scala

This PR provides the minimum changes to get the register journey "working" - i.e. re-enabled so that, locally, a user can progress through to the "CYA" page and submit a request.
The "service" enrolment for register journey defaults to CDS - so CDS has been added to the list of supported services.
However, we don't want to support "CDS" as part of the subscribe journey - so the "cds/subscribe" url has been added to the block list.

ECC-159 - un-block 'register' route and default to 'cds' 

---

test/integration/HandleSubscriptionConnectorSpec.scala
test/integration/Save4LaterConnectorSpec.scala
test/util/externalservices/AuditService.scala

Following another random Jenkins build failure I've taken a look at the "un-matched" wiremock calls when running our ITs.
Don't know if this will fix the problem but it should remove some of the clutter.

BAU - tidy up integration tests - stop logs re un-matched wiremock calls

---

conf/messages-ecc.en
conf/messages.en
test/unit/views/YouCantUseServiceSpec.scala

Welsh did not need changing - it already translates to "public holidays"

ECC-323 - small opening time content change

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/helpers/DateFormatter.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/migration/migration_success.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/sub01_outcome_processing.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/sub01_outcome_rejected.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/sub02_eori_already_associated.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/sub02_eori_already_exists.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/sub02_subscription_in_progress.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/subscription_outcome.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/subscription_outcome_fail.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/subscription_outcome_pending.scala.html
test/unit/views/DateFormatterSpec.scala
test/unit/views/registration/SubscriptionCompleteSpec.scala
test/unit/views/subscription/Sub01OutcomeProcessingSpec.scala
test/unit/views/subscription/Sub01OutcomeRejectedSpec.scala
test/unit/views/subscription/SubscriptionOutcomeFailSpec.scala
test/unit/views/subscription/SubscriptionOutcomePendingSpec.scala

- also converts abbreviated months (Jan) to full name (January)
Dates are passed as strings to most (not all) of our "confirmation/error" screens.  As a result they cannot be easily translated using the HMRC play LanguageUtils.
The use of dates is wide-spread throughout the service.  So to minimise the impact of this fix I've created a 'helper' in the view package that will attempt to convert a date string of the form "dd MMM yyyy" to a LocalDate and then translate it (where required).
If this fails (e.g. date is in a different format for some reason) the helper returns the input date string.  So the fix should be fairly safe to deploy.

ECC-368 - fix for translating dates on confirmation screens

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala

When HC has no session id - the user is not logged in.  So it doesn't make sense to try and update the database.

BAU - prevent exceptions when trying to keep alive

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/YouCannotUseServiceController.scala

From the ticket https://jira.tools.tax.service.gov.uk/browse/ECC-975
1. If Enrolment already exists for a logged in User they are redirected to `unable-to-use-id` page (page mentioned in this ticket)
2. On `unable-to-use-id` page load a cache check is done: if Eori number is in the cache -> `unable-to-use-id` page is loaded, if not -> user is redirected to `/matching/use-this-eori` where user can confirm that this is Eori they want to use and continue subscription journey.
3. Very important last step: cache is deleted just after cache check in step 2. What this means - if a user refreshes the `unable-to-use-id` page or clicks Welsh translation they will get always redirected to `matching/use-this-eori` page (as cache was deleted on the first page load/visit).
This gets rid of cache …

ECC-975 Remove unnecessary cache deletion

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/EnrolmentAlreadyExistsController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/auth/AccessController.scala
test/unit/controllers/ApplicationControllerSpec.scala
test/unit/filters/UserTypeFilterSpec.scala

Changing the order of the checks during authorisation call - https://jira.tools.tax.service.gov.uk/browse/ECC-981.
Previous order:
1. Check User type (Agent check) & email check (checking Cred Role was included in User Type check)
2. Check enrolment
New order:
1. Check User type (Agent check) & email check
2. Check enrolment
3. Organisation Cred Role Assistant check
(as in https://github.com/hmrc/customs-rosm-frontend/pull/62 and https://github.com/hmrc/eori-common-component-registration-frontend/pull/29)

ECC-981 refactor access logic to check enrolment at a later stage

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/SubscriptionRecoveryController.scala
test/unit/controllers/registration/SubscriptionRecoveryControllerSpec.scala

Adding customs-rosm-frontend `bundleId` enrichment logic in ECC to support subscription.
More info in: [ECC-1083](https://jira.tools.tax.service.gov.uk/browse/ECC-1083).

ECC-1083 migrating subscription bundleId logic from SCDS

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/EmailController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/email/CheckYourEmailController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/email/WhatIsYourEmailController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/Save4LaterService.scala
test/unit/controllers/EmailControllerSpec.scala
test/unit/controllers/email/CheckYourEmailControllerSpec.scala
test/unit/controllers/email/WhatIsYourEmailControllerSpec.scala
test/unit/services/Save4LaterServiceSpec.scala

- add new key to `save4later` service to separate the CDS Email address storage for the short journey
- enforces for every new CDS subscription to ask for Email input during short journey

Introduce new save4later key for CDS auto-enrolment journey

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/EmailController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/email/CheckYourEmailController.scala
test/unit/controllers/EmailControllerSpec.scala
test/unit/controllers/email/CheckYourEmailControllerSpec.scala

Making sure email is saved in `save4later` only after is successfully updated via SUB22 and customs-datastore calls.

ECC-1221 save verified email after successful update

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/CdsErrorHandler.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/subscription/CompletedEnrolmentController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
build.sbt
test/integration/SessionCacheServiceSpec.scala
test/unit/controllers/CdsErrorHandlerSpec.scala
test/unit/controllers/subscription/CompletedEnrolmentControllerSpec.scala

Currently, `DataUnavailableException` is thrown in most cases when reading non-existent element from session cache.
For consistency I’ve updated methods in `SessionCache` which read data from session cache to throw this exception instead of `IlegalArgumentException`.
`DataUnavailableException` usage report: [data_unavailable_exception_usage.txt](https://github.com/hmrc/eori-common-component-frontend/files/9280377/data_unavailable_exception_usage.txt)
SessionCache is currently cleared on:
- Sign Out / Log Out
- Display of Subscription result (last page from Long Journey, Sub02Controller)
- Sub01 Subscription Status result (pending / fail)
Proposed solution based on previous discussions:
On `DataUnavailableException` redirect the user to the beginning of the journey. In a scenario where the …

ECC-1233 redirect on DataUnavailableException

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/UpdateVerifiedEmailConnector.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/UpdateVerifiedEmailService.scala
test/unit/connector/UpdateVerifiedEmailConnectorSpec.scala

Current auditing events in `UpdateVerifiedEmailConnector` can be misleading as `003` Email Error comes back as HTTP 200 response (error encoded in the body) and would be visible in Splunk, therefore:
- moved both of the audit events `changeEmailAddressConfirmed` and `changeEmailAddressVerified` to be executed only when the response contains expected (correct) Json body
- changed log level to track success to Info to help ruling out duplicate call issue

Move audit events and logging change

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/has_existing_eori.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/helpers/inputDate.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/migration/check_your_details.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/confirm_contact_address.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/contact_address.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/date_of_establishment.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription/reg06_eori_already_linked.scala.html
build.sbt
project/build.properties
project/plugins.sbt

- upgrading service to use SBT `1.5.x`
- upgrading Play Framework as SBT `1.5.x` is supported only from Play `2.8.8`

ECC-758 upgrading SBT and dependencies

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/migration/what_is_your_eori_check_failed.scala.html

Fix based on the results of the ECC accessibility audit: 
https://build.tax.service.gov.uk/job/EORI%20Common%20Component/job/eori-common-component-a11y-subscription-tests/Accessibility_20Check_20Report/

Accessibility fix - headings out of order

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/httpparsers/HttpErrorResponse.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/EmailController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/email/CheckYourEmailController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/SubscriptionRecoveryController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/subscription/UpdateVerifiedEmailService.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/email_error_template.scala.html
conf/messages.cy
conf/messages.en
test/unit/controllers/EmailControllerSpec.scala
test/unit/controllers/email/CheckYourEmailControllerSpec.scala
test/unit/controllers/registration/SubscriptionRecoveryControllerSpec.scala
test/unit/services/subscription/UpdateVerifiedEmailServiceSpec.scala

Add better error handling so that Email Update 003 errors can be handled gracefully for https://jira.tools.tax.service.gov.uk/browse/ECC-1224
Added explicit audit event for 003 failure:
```
{
"auditSource": "eori-common-component-frontend",
"auditType": "changeEmailAddressCouldNotBeProcessed",
"eventId": "ea027401-6c6e-4a3d-8e25-21b84d95b158",
"tags": {
"clientIP": "-",
"path": "http://localhost:6753/update-verified-email",
"X-Session-ID": "session-25477e5b-c236-4ef4-986e-60f245bbe2e5",
"Akamai-Reputation": "-",
"X-Request-ID": "govuk-tax-0c540260-909a-426e-965f-312c26b3ef5c",
"deviceID": "xxxx",
"clientPort": "-",
"transactionName": "UpdateVerifiedEmailRequestSubmitted"
},
"detail": {
"newEmailAddress": "200Fail@email.com",
"eori": "GB123456789123",
"status": "003 - Request could not be …
```

ECC-1224 add logic to handle 003 Errors

---

build.sbt
project/build.properties
test/base/UnitSpec.scala
test/common/pages/WebPage.scala
test/integration/AllTheCountriesSpec.scala
test/integration/SessionCacheServiceSpec.scala
test/unit/connector/UpdateVerifiedEmailConnectorSpec.scala
test/unit/controllers/ApplicationControllerSpec.scala
test/unit/controllers/migration/NameDobSoleTraderControllerSpec.scala
test/unit/controllers/migration/NameIDOrgControllerSpec.scala
test/unit/controllers/registration/UserLocationControllerSpec.scala
test/unit/controllers/subscription/AddressLookupErrorControllerSpec.scala
test/unit/controllers/subscription/AddressLookupPostcodeControllerSpec.scala
test/unit/controllers/subscription/AddressLookupResultsControllerSpec.scala
test/unit/controllers/subscription/CompanyRegisteredCountryControllerSpec.scala
test/unit/controllers/subscription/ConfirmContactAddressControllerSpec.scala
test/unit/controllers/subscription/EoriUnableToUseControllerSpec.scala
test/unit/controllers/subscription/EoriUnableToUseSignoutControllerSpec.scala
test/unit/models/JourneySpec.scala
test/unit/models/ServiceSpec.scala
test/unit/services/countries/CountriesSpec.scala
test/unit/services/organisation/OrgTypeLookupSpec.scala
test/unit/services/subscription/CdsSubscriberSpec.scala
test/unit/util/RequireSpec.scala
test/util/builders/AuthActionMock.scala

I tried upgrading to bootstrap play 7.11.0 which resulted in test failures. So upgraded to latest versions of the test libraries, which required code changes. The tests still failed. Rolled back to bootstrap play 5.8.0 which is the earliest version withy the security fix and the tests passed. Integrated a bootstrap play upgrade to 5.16.0 introduced in main by @povilas.

ECC-1422: update play library for security issue

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/registration/RegisterWithEoriAndIdController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/subscription/SubmissionCompleteData.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
test/integration/SessionCacheServiceSpec.scala
test/unit/controllers/registration/RegisterWithEoriAndIdControllerSpec.scala

Prevent a `DataUnavailableException` being thrown on the pending screen when either refreshing or using the language switcher. We store subscriptionDetails and processingDate as an additional cache field so we can wipe other cache items to prevent data being available if user goes back to previous page in the journey

ECC-1917: Prevent DataUnavailableException welsh toggle - Pending
